name: bird_classifier
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=3.5.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.1.0
  - brotlipy=0.7.0
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=39.0.1
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - expat=2.4.9
  - fontconfig=2.14.1
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - intel-openmp=2023.1.0
  - ipykernel=6.19.2
  - ipython_genutils=0.2.0
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=8.2.0
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_server=1.23.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.22.1
  - krb5=1.19.4
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libclang13=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libllvm14=14.0.6
  - libpng=1.6.39
  - libpq=12.9
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.3
  - libxslt=1.1.37
  - lightgbm=3.3.5
  - lxml=4.9.2
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.2.1
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=2.8.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - notebook-shim=0.2.2
  - nspr=4.33
  - nss=3.74
  - numpy-base=1.24.3
  - openssl=1.1.1u
  - packaging=23.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.1
  - platformdirs=2.5.2
  - ply=3.11
  - pooch=1.4.0
  - prometheus_client=0.14.1
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - pytorch=2.0.1
  - pytz=2022.7
  - pyyaml=6.0
  - pyzmq=25.0.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.4.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.28.2
  - send2trash=1.8.0
  - setuptools=66.0.0
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - tzdata=2023c
  - urllib3=1.26.15
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==1.4.0
      - asttokens==2.2.1
      - astunparse==1.6.3
      - beautifulsoup4==4.9.3
      - cachetools==5.3.0
      - catboost==1.0.3
      - click==8.1.3
      - cmake==3.26.4
      - comm==0.1.4
      - cycler==0.11.0
      - executing==1.2.0
      - filelock==3.11.0
      - flatbuffers==2.0.7
      - fqdn==1.5.1
      - gast==0.4.0
      - google-auth==2.17.3
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - greenlet==2.0.2
      - grpcio==1.53.0
      - h5py==3.8.0
      - huggingface-hub==0.13.4
      - ipython==8.14.0
      - ipywidgets==8.1.0
      - isoduration==20.11.0
      - jedi==0.19.0
      - joblib==1.2.0
      - jsonpointer==2.3
      - jupyter-contrib-core==0.4.2
      - jupyter-contrib-nbextensions==0.7.0
      - jupyter-highlight-selected-word==0.2.0
      - jupyter-nbextensions-configurator==0.6.1
      - jupyterlab-widgets==3.0.8
      - jupyterthemes==0.20.0
      - keras==2.7.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.4
      - lesscpy==0.15.1
      - libclang==16.0.0
      - lit==16.0.6
      - markdown==3.4.3
      - matplotlib==3.3.4
      - nltk==3.6.1
      - notebook==6.4.0
      - numpy==1.20.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - pandas==1.2.4
      - patsy==0.5.3
      - phik==0.12.3
      - pillow==8.4.0
      - plotly==5.4.0
      - prompt-toolkit==3.0.39
      - protobuf==4.22.3
      - psycopg2-binary==2.9.2
      - py4j==0.10.9
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pygments==2.15.1
      - pyparsing==3.0.9
      - pyspark==3.0.2
      - graphviz==0.20.1
      - regex==2022.3.15
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - sacremoses==0.0.53
      - scikit-learn==0.24.1
      - scipy==1.8.0
      - seaborn==0.11.1
      - sqlalchemy==1.4.15
      - stack-data==0.6.2
      - statsmodels==0.13.2
      - tenacity==8.2.2
      - tensorboard==2.12.2
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.7.0
      - tensorflow-estimator==2.7.0
      - tensorflow-io-gcs-filesystem==0.32.0
      - termcolor==2.2.0
      - threadpoolctl==3.1.0
      - tokenizers==0.10.3
      - torchvision==0.15.2
      - tqdm==4.65.0
      - traitlets==5.9.0
      - transformers==4.12.5
      - triton==2.0.0
      - typing-extensions==4.7.1
      - uri-template==1.2.0
      - wcwidth==0.2.6
      - webcolors==1.13
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.8
      - wrapt==1.15.0
